### ISSUE TITLE
Adaptação do relatório de resultado final para turmas multisseriadas

### ISSUE THREAD

**Issue by netocx** [portabilis/i-educar-reports-package#101]
MENU:

i-Educar - Escola > Documentos > Resultados > Resultado Final

DESCRIÇÃO:

O relatório em questão apresenta apenas os alunos da série principal, não sendo possível gerar o relatório para os alunos das demais séries da turma.

Funciona corretamente com os ajustes a abaixo, haveria algo mais a observar?

adicionada a linha:
40             $serie = $this->args['serie'] ?: 0;

removidas as linhas:
74             AND turma.ref_cod_curso = curso.cod_curso
75             AND turma.ref_ref_cod_serie = serie.cod_serie

adicionada a linha:
103           AND matricula.ref_ref_cod_serie = {$serie}

AMBIENTE DE TESTE:
Ubuntu 20.04.4 LTS
PHP 8.1.8
i-Educar 2.7.4

**Comment by marcosoliveirasoares94** [comment]
@netocx, seria possível colocar o print do código antes da alteração mencionada por você e outro print da alteração mencionada, acredito que seja mais fácil de avaliar.

**Comment by marcosoliveirasoares94** [comment]
@netocx, as alterações está um pouco diferente da orientação mencionada no [PR-99](https://github.com/portabilis/i-educar-reports-package/pull/99)

Recomendo que você siga criando um PR para essa issue, e dessa forma ele pode ser aceito, rejeitado ou discutido junto com a Portabilis, com as pessoas @Bonot e/ou @edersoares.
