### ISSUE TITLE
Instalação dos Relatórios no i-Educar 2.1

### ISSUE THREAD

**Issue by rohanbernartt** [portabilis/i-educar-reports-package#53]
Olá,
Depois de realizar a instalação dos relatórios, quando vou gerar algum, na saída do relatório aparece seguinte mensagem:

> Ocorreu um erro ao emitir o relatório.
> Detalhes: Your report has an error and couldn't be processed! Try to output the command using the function `output();` and run it manually in the console.`

**Comment by edersoares** [comment]
@rohanbernartt acredito que você já deva ter resolvido este problema através do fórum, se possível fechar a issue, senão deixe mais detalhes para podermos ajudar 😄
