### ISSUE TITLE
Erro na instalação dos relatórios na release 2.1.2 do i-Educar

### ISSUE THREAD

**Issue by carolinesalib** [portabilis/i-educar-reports-package#56]
## Descrição
Obtive alguns erros quando fui instalar o i-Educar esta semana na minha máquina.

1. O primeiro erro foi que a migração `AddBirthdaysReportMenu` ainda está utilizando o phinx, e acredito que esta biblioteca não está mais incluída nos pacotes do i-Educar.
2. O outro erro obtive ao tentar instalar o pacote de relatórios em uma base que já continha o schema `relatorio` (estou migrando bases antigas que já continham dados), e por isto não consegui rodar o script inicial pois gerava alguns erros já que a maioria das views e functions já existiam.

Fiz alguns pull requests com as alterações que fiz para resolver isto:
https://github.com/portabilis/i-educar-reports-package/pull/54
https://github.com/portabilis/i-educar-reports-package/pull/55

Caso as alterações não sejam relevantes fiquem a vontade para fechar tanto a issue quanto os pull requests. :blush:

**Comment by edersoares** [comment]
Oii, @carolinesalib, deixa eu te pedir, você fez a instalação executando os comandos do readme ou usou a versão de instalação para o servidor?

**Comment by carolinesalib** [comment]
Oi, @edersoares! Usei os comandos do readme na pasta rais do i-Educar.

```
docker-compose exec php artisan reports:install
docker-compose exec php artisan migrate
```

**Comment by edersoares** [comment]
@carolinesalib obrigado pela contribuição, realmente ambos os PRs foram uteis. Fiz os testes e agora está funcionando corretamente :) 

Iremos fechar a issue ;)
