### ISSUE TITLE
Parecer descritivo

### ISSUE THREAD

**Issue by ieducarcda** [portabilis/i-educar-reports-package#65]
Bom dia, venho sugerir que seja implantado relatorio do PARECER DESCRITIVO das turmas do 1 ao 5 ano, pois no sistema tem apenas o local para que o professor lance o parecer por semestre, porem nao exite a opcao de geracao de nenhum tipo de saida, seja relatorio ou documento tipo no boletim.

**Comment by edersoares** [comment]
Implementação https://github.com/portabilis/i-educar-reports-package/pull/80.
