### ISSUE TITLE
Histórico escolar do EJA

### ISSUE THREAD

**Issue by ieducarcda** [portabilis/i-educar-reports-package#66]
Bom dia, verifiquei que o historico escolar do EJA nao funciona, ja das turmas do 1 ao 9 ano funciona corretamente. Peco que voces verifiquei???

**Comment by Bonot** [comment]
Olá, @ieducarcda, o histórico atual disponibilizado na comunidade realmente não trabalha com informações do EJA.

Um novo modelo foi disponibilizado na nova versão, para mais detalhes acesse o pull request: https://github.com/portabilis/i-educar-reports-package/pull/75
