### ISSUE TITLE
Erro ao emitir relatorios

### ISSUE THREAD

**Issue by evertonvps** [portabilis/i-educar-reports-package#90]
Pessoal, estou com problemas ao emitir relatorios seguindo o processo de **Instalação em servidor** . Fiz a mesma instalalacao no docker e nao tive problemas.

`Exception {#2141 ▼
  #message: "12:56:50,397 ERROR JRFillSubreport:879 - Fill 1: exception"
  #code: 1
  #file: "/var/www/ieducar/vendor/cossou/jasperphp/src/JasperPHP/JasperPHP.php"
  #line: 189
  trace: {▼
    /var/www/ieducar/vendor/cossou/jasperphp/src/JasperPHP/JasperPHP.php:189 {▼
      JasperPHP\JasperPHP->execute($run_as_user = false) …
      › if( $return_var != 0 && isset($output[0]) )
      ›     throw new \Exception($output[0], 1);
      › elseif( $return_var != 0 ) 
    }
    /var/www/ieducar/ieducar/lib/Portabilis/Report/ReportFactoryPHPJasper.php:118 {▶}
    /var/www/ieducar/ieducar/lib/Portabilis/Report/ReportCore.php:116 {▶}
    /var/www/ieducar/ieducar/lib/Portabilis/Controller/ReportCoreController.php:125 {▶}
    /var/www/ieducar/ieducar/lib/Portabilis/Controller/ReportCoreController.php:78 {▶}
    /var/www/ieducar/ieducar/intranet/include/clsCadastro.inc.php:201 {▶}
    /var/www/ieducar/ieducar/intranet/include/clsBase.inc.php:50 {▶}
    /var/www/ieducar/ieducar/intranet/include/clsBase.inc.php:130 {▶}
    /var/www/ieducar/ieducar/lib/Core/View.php:120 {▶}
    /var/www/ieducar/ieducar/lib/Core/Controller/Page/Abstract.php:491 {▶}
    /var/www/ieducar/ieducar/lib/CoreExt/Controller/Dispatcher/Strategy/PageStrategy.php:106 {▶}
    /var/www/ieducar/ieducar/lib/CoreExt/Controller/Front.php:89 {▶}
    /var/www/ieducar/ieducar/module/index.php:26 {▶}
    /var/www/ieducar/app/Http/Controllers/LegacyController.php:95 {▶}
    /var/www/ieducar/app/Http/Controllers/LegacyController.php:80 {▶}
    /var/www/ieducar/app/Http/Controllers/LegacyController.php:234 {▶}
    /var/www/ieducar/app/Http/Controllers/LegacyController.php:287 {▶}
    /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:54 {▶}
    /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:45 {▶}
    /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Routing/Route.php:262 {▶}
    /var/www/ieducar/vendor/laravel/framework/src/Illuminate/Routing/Route.php:205 {▶}`

**Comment by edersoares** [comment]
Você instalou o OpenJDK no servidor?

**Comment by evertonvps** [comment]
> 

Sim. openjdk 8 instalado. Interessante que o relatorio DistributionOfUniformPerStudent exibe em branco por nao ter dados, porem os outros explodem o mesmo exception.

**Comment by evertonvps** [comment]
problema resolvido...
O erro foi ter instalado a jre... 
`apt install openjdk-8-jre-headless`
Resolvi somente removendo e instalando novamente:
`apt remove openjdk-8-jre-headless`
`apt-get autoremove openjdk-8-jre-headless`
`apt-get update`
`apt-get install openjdk-8-jdk -y`
