### ISSUE TITLE
Erro no relatório de resultados finais

### ISSUE THREAD

**Issue by netocx** [portabilis/i-educar-reports-package#94]
MENU:
Escola -> Documentos -> Resultados -> Resultado final

DESCRIÇÃO:
O relatório prevê nas estatísticas informar o percentual de alunos transferidos ou que abandonaram, porém, não mostra esses alunos no relatório e nem o seu percentual.

![image](https://user-images.githubusercontent.com/81721721/148702393-84faeea7-4a0a-4137-b56b-d940af952ce7.png)

OBSERVAÇÕES:

AMBIENTE:
Plataforma utilizada: instalação direta
Sistema operacional e versão: Ubuntu 20.04
Navegador e versão: Chrome 96.0.4664.110
Outros detalhes importantes: i-Educar 2.6.7

**Comment by jrbarros** [comment]
Olá @netocx, novamente muito obrigado pelo contribuição.

Preciso de mais dados para determinar onde se encontra o problema, é possível nos enviar o cenário onde os alunos não estão sendo apresentados? Tipo, uma base de dados simulando o problema, prints, videos etc. isso nos ajudará a ser mais assertivos na identificação. 

Deste de já agradeço a contribuição.

**Comment by netocx** [comment]
Obrigado pela atenção @jrbarros,
Então, embora existam alunos em abandono ou transferidos o relatório só mostra aprovados e reprovados... deve haver algum filtro para mostrar somente as matriculas ativas algo assim. Dessa forma o relatório fica inconsistente, pois dá a impressão de que eram só esses os alunos da turma. Não tenho um ambiente de desenvolvimento montado pra verificar melhor, mas é basicamente isso em todas as turmas de todas as escolas.

**Comment by netocx** [comment]
[Lista de alunos.pdf](https://github.com/portabilis/i-educar-reports-package/files/7838917/Lista.de.alunos.pdf)
[FinalResult.pdf](https://github.com/portabilis/i-educar-reports-package/files/7838921/FinalResult.pdf)

**Comment by netocx** [comment]
RESOLVIDO, lembrei de ter feito alterações no meu FinalResultReport.php na tentativa de resolver o erro do post...
https://forum.ieducar.org/t/erro-interno-em-resultados-finais/1562/7

Reinstalei e funciona normalmente, desculpem o transtorno!
