### ISSUE TITLE
Ao tentar instalar:  There are no commands defined in the "community:reports" namespace

### ISSUE THREAD

**Issue by hermesalvesbr** [portabilis/i-educar-reports-package#98]
Boa noite,

Estou tentando instalar o resports no i-educar 2.6.8. Mas me exibe a seguinte mensagem de erro: 

```
 There are no commands defined in the "community:reports" namespace.  
                                                                       
chmod: cannot access 'ieducar/modules/Reports/ReportSources': No such file or directory
Compiling reports files..
sh: line 0: cd: /home/myusr/public_html/ieducar/modules/Reports/ReportSources: No such file or directory
Nothing to migrate.
[myusr@hydra www]$ php artisan reports:install
chmod: cannot access 'ieducar/modules/Reports/ReportSources': No such file or directory
Compiling reports files..
sh: line 0: cd: /home/myusr/public_html/ieducar/modules/Reports/ReportSources: No such file or directory
Nothing to migrate.

```

# Observei que não foi criado *Reports* dentro de modules, então eu criei manualmente.
Agora o único erro que permanece é: 

![Screenshot_20220414_174132](https://user-images.githubusercontent.com/379850/163471867-c4a9932c-7afa-4532-ad88-97e1b866432c.png)

Agradeço antecipadamente qualquer orientação.

**Comment by hermesalvesbr** [comment]
Fui no fórum procurar mais informações, e nesta discussão foi recomendado alguns comandos:
https://forum.ieducar.org/t/resolvido-erro-instalacao-do-relatorio-ieducar/1436/10?page=2

```
cd /var/www/ieducar && sudo rm -rf packages/portabilis/i-educar-reports-package
 git clone https://github.com/portabilis/i-educar-reports-package.git packages/portabilis/i-educar-reports-package
sudo composer update --plug-and-play --no-interaction
sudo php artisan legacy:link
sudo php artisan community:reports:link
sudo php artisan reports:install
sudo php artisan storage:link
```
## Mas aparece outro erro relacionado ao plug and play
Então também adicionar o composer install pra tentar fazer o plug and play error desaparecer, _mas não funcionou também_. 
```
[myuser@hydra www]$ ./reports.sh 
Cloning into 'packages/portabilis/i-educar-reports-package'...
remote: Enumerating objects: 1771, done.
remote: Counting objects: 100% (41/41), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 1771 (delta 20), reused 6 (delta 1), pack-reused 1730
Receiving objects: 100% (1771/1771), 953.91 KiB | 5.42 MiB/s, done.
Resolving deltas: 100% (1208/1208), done.

                                                
  The "--plug-and-play" option does not exist.  
                                                

update [--with WITH] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>...]

Symbol link created for: intranet/fonts
Symbol link created for: intranet/imagens
Symbol link created for: intranet/scripts
Symbol link created for: intranet/static
Symbol link created for: intranet/styles
Symbol link created for: intranet/tmp
Symbol link created for: modules
                                                                
  There are no commands defined in the "community:reports" namespace.  
               
```                                                        
Compiling reports files..
Nothing to migrate.
The [/home/myuser/public_html/public/storage] link has been connected to [/home/myuser/public_html/storage/app/public].
The links have been created.
[myuser@hydra www]$ 

### Mais alguma ideia de como fazer funcionar?

**Comment by edersoares** [comment]
@hermesalvesbr houve quebra de versão no Composer 2.3, você vai precisar rodar `composer self-update --2.2` para usar a versão 2.2 até que o i-Educar atualize a versão do [composer-plug-and-play](https://github.com/edersoares/composer-plug-and-play).

**Comment by hermesalvesbr** [comment]
Boa tarde, 

Este comando mudou a mensagem de erro: 

```
php artisan community:reports:link

   ErrorException 

  symlink(): File exists

  at packages/portabilis/i-educar-reports-package/src/Commands/CommunityReportsLinkCommand.php:37
     33▕         if (is_link($target)) {
     34▕             unlink($target);
     35▕         }
     36▕ 
  ➜  37▕         symlink($source, $target);
     38▕ 
     39▕         $this->info("Symbol link created in: {$target}");
     40▕     }
     41▕ }

  1   packages/portabilis/i-educar-reports-package/src/Commands/CommunityReportsLinkCommand.php:37
      symlink("/var/www/ieducar/packages/portabilis/i-educar-reports-package/src/Commands/../../ieducar", "/var/www/ieducar/ieducar/modules/Reports")

      +13 vendor frames 
  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

- Tentei remover o link manualmente, não funcionou
- Fiz um composer new-install, não funcionou
- Removi o package report todo, não funcionou
- Tentei artisan cache route view clear, não funcionou. 

_Obrigado pela ajuda!_

**Comment by edersoares** [comment]
@hermesalvesbr use o comando `sudo composer plug-and-play:update --no-interaction` ao invés de `sudo composer update --plug-and-play --no-interaction`

**Comment by hermesalvesbr** [comment]
Boa noite @edersoares obrigado por mais uma vez desprender seu tempo com isto.

Percebo que o problema está na hora do link, seu comando agora executou, mas a mensagem de erro é a mesma.

**Comandos que executei**
```
cd /var/www/ieducar && sudo rm -rf packages/portabilis/i-educar-reports-package
 git clone https://github.com/portabilis/i-educar-reports-package.git packages/portabilis/i-educar-reports-package
sudo composer plug-and-play:update --no-interaction
sudo php artisan legacy:link
sudo php artisan community:reports:link
sudo php artisan reports:install
sudo php artisan storage:link
```
Demonstração do terminal: 
![image](https://user-images.githubusercontent.com/379850/163878850-77c998d4-097d-4fe3-bdb0-90c3f45e87b1.png)

**Comment by edersoares** [comment]
@hermesalvesbr pelo que pude ver nas mensagens "Discovered Package:" o pacote `portabilis/i-educar-reports-package` não está presente, acredito que seja porque está usando a versão 2.3 do Composer ainda. 

Execute `composer --version` para saber a versão.

**Comment by hermesalvesbr** [comment]
Boa tarde @edersoares  você tinha razão, estava ainda com a 2.3. Agora está com a **Composer version 2.2.12 2022-04-13 16:42:25**
![image](https://user-images.githubusercontent.com/379850/164073487-402991d8-f346-4530-a5c6-bb4ae5a4f81d.png)

Só que agora voltamos ao problema de **23 horas** atrás.

**Comment by edersoares** [comment]
@hermesalvesbr apague o diretório `ieducar/modules/Reports` e rode o comando novamente.

**Comment by hermesalvesbr** [comment]
Bom dia @edersoares , o filho nasceu! :smile: 

Funcionou perfeitamente, como contribuição para a comunidade, fiz um pequeno shell script com todos os comandos que funcionam.

https://gist.github.com/hermesalvesbr/64087fb185e86802d316a254c669cdc6

**Obrigado pela atenção dedicada.**
